export const userProfileStrings = {
  title: "My Profile",
  labels: {
    fullName: "Full Name",
    email: "Email",
    mobileNumber: "Mobile Number",
    designation: "Designation",
    gender: "Gender",
    currentTier: "Current Tier",
    roles: "Roles",
    dateCreated: "Member Since",
  },
  uploadImage: "Upload Photo",
  uploadSuccess: "Profile photo updated!",
  uploadError: "Failed to upload photo. Please try again.",
  loading: "Loading profile...",
  error: "Failed to load profile.",
  retry: "Retry",
  sections: {
    personalInfo: "Personal Information",
    workDetails: "Work Details",
  },
  userLabel: "User: ",
  upload: {
    selectImage: "Please select an image file.",
    imageTooLarge: "Image must be under 5MB.",
    uploading: "Uploading...",
    changePhoto: "Change Photo",
    hint: "JPG, PNG up to 5MB. Drag and drop or click to upload.",
  },
  deleting: "Deleting...",
  loadDetailError: "Failed to load user details.",
  loadProfileError: "Failed to load profile. Please try again.",
  errorTitle: "Error",
  uploadConfig: {
    maxSize: 5 * 1024 * 1024,
    acceptedTypes: "image/png,image/jpeg,image/jpg",
    typePrefix: "image/",
  },
  createUserTitle: "Create User",
} as const;
