/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AssessmentResultResponseDto,
  AssessmentSubmitRequestDto,
  GetApiV1AssessmentParams,
  GetApiV1AssessmentUserUserIdAssessmentHistoryParams,
  PaginatedAssessmentHistoryResponseDto,
  PaginatedAssessmentsDto,
  PostApiV1AssessmentBody,
  QuestionDto,
  SubmitAssessmentResponseDto,
  SuccessResponse,
  UpdateAssessmentRequestDto,
  UpdateQuestionRequestDto
} from '../../models';




  export const getAssessment = (axiosInstance: AxiosInstance = axios.default) => {
const postApiV1Assessment = (
    postApiV1AssessmentBody?: PostApiV1AssessmentBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {const formData = new FormData();
if(postApiV1AssessmentBody?.CourseId !== undefined) {
 formData.append(`CourseId`, postApiV1AssessmentBody.CourseId);
 }
if(postApiV1AssessmentBody?.Title !== undefined) {
 formData.append(`Title`, postApiV1AssessmentBody.Title);
 }
if(postApiV1AssessmentBody?.Description !== undefined) {
 formData.append(`Description`, postApiV1AssessmentBody.Description);
 }
if(postApiV1AssessmentBody?.PassingMark !== undefined) {
 formData.append(`PassingMark`, postApiV1AssessmentBody.PassingMark.toString())
 }
if(postApiV1AssessmentBody?.DurationMinute !== undefined) {
 formData.append(`DurationMinute`, postApiV1AssessmentBody.DurationMinute.toString())
 }
if(postApiV1AssessmentBody?.QuestionFile !== undefined) {
 formData.append(`QuestionFile`, postApiV1AssessmentBody.QuestionFile);
 }

    return axiosInstance.post(
      `/api/v1/assessment`,
      formData,options
    );
  }
const getApiV1Assessment = (
    params?: GetApiV1AssessmentParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedAssessmentsDto>> => {
    return axiosInstance.get(
      `/api/v1/assessment`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const postApiV1AssessmentIdSubmit = (
    id: string,
    assessmentSubmitRequestDto?: AssessmentSubmitRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubmitAssessmentResponseDto>> => {
    return axiosInstance.post(
      `/api/v1/assessment/${id}/submit`,
      assessmentSubmitRequestDto,options
    );
  }
const getApiV1AssessmentIdQuestion = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<QuestionDto[]>> => {
    return axiosInstance.get(
      `/api/v1/assessment/${id}/question`,options
    );
  }
const putApiV1AssessmentId = (
    id: string,
    updateAssessmentRequestDto?: UpdateAssessmentRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.put(
      `/api/v1/assessment/${id}`,
      updateAssessmentRequestDto,options
    );
  }
const deleteApiV1AssessmentId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.delete(
      `/api/v1/assessment/${id}`,options
    );
  }
const getApiV1AssessmentIdResult = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssessmentResultResponseDto>> => {
    return axiosInstance.get(
      `/api/v1/assessment/${id}/result`,options
    );
  }
const putApiV1AssessmentQuestionId = (
    id: string,
    updateQuestionRequestDto?: UpdateQuestionRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.put(
      `/api/v1/assessment/question/${id}`,
      updateQuestionRequestDto,options
    );
  }
const deleteApiV1AssessmentQuestionId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.delete(
      `/api/v1/assessment/question/${id}`,options
    );
  }
const getApiV1AssessmentExportTemplate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/assessment/export-template`,options
    );
  }
const getApiV1AssessmentUserUserIdAssessmentHistory = (
    userId: string,
    params?: GetApiV1AssessmentUserUserIdAssessmentHistoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedAssessmentHistoryResponseDto>> => {
    return axiosInstance.get(
      `/api/v1/assessment/user/${userId}/assessment-history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {postApiV1Assessment,getApiV1Assessment,postApiV1AssessmentIdSubmit,getApiV1AssessmentIdQuestion,putApiV1AssessmentId,deleteApiV1AssessmentId,getApiV1AssessmentIdResult,putApiV1AssessmentQuestionId,deleteApiV1AssessmentQuestionId,getApiV1AssessmentExportTemplate,getApiV1AssessmentUserUserIdAssessmentHistory}};
export type PostApiV1AssessmentResult = AxiosResponse<SuccessResponse>
export type GetApiV1AssessmentResult = AxiosResponse<PaginatedAssessmentsDto>
export type PostApiV1AssessmentIdSubmitResult = AxiosResponse<SubmitAssessmentResponseDto>
export type GetApiV1AssessmentIdQuestionResult = AxiosResponse<QuestionDto[]>
export type PutApiV1AssessmentIdResult = AxiosResponse<SuccessResponse>
export type DeleteApiV1AssessmentIdResult = AxiosResponse<SuccessResponse>
export type GetApiV1AssessmentIdResultResult = AxiosResponse<AssessmentResultResponseDto>
export type PutApiV1AssessmentQuestionIdResult = AxiosResponse<SuccessResponse>
export type DeleteApiV1AssessmentQuestionIdResult = AxiosResponse<SuccessResponse>
export type GetApiV1AssessmentExportTemplateResult = AxiosResponse<void>
export type GetApiV1AssessmentUserUserIdAssessmentHistoryResult = AxiosResponse<PaginatedAssessmentHistoryResponseDto>
