/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AdminCourseSummaryDto,
  AssessmentOverviewDto,
  CourseContentResponseDto,
  CourseOverviewDto,
  CourseProgressResponseDto,
  CourseSummaryDto,
  CreateForumMessageRequestDto,
  ForumMessageDto,
  GetApiV1CourseCourseIdLeaderboardParams,
  GetApiV1CourseIdAssessmentHistoryParams,
  GetApiV1CourseParams,
  LeaderboardDto,
  PaginatedAssessmentHistoryDto,
  PaginatedCoursesDto,
  PostApiV1CourseBody,
  PutApiV1CourseCourseIdBody,
  RefTermDto,
  SuccessResponse
} from '../../models';




  export const getCourse = (axiosInstance: AxiosInstance = axios.default) => {
const getApiV1CourseCourseIdAssessmentOverview = (
    courseId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssessmentOverviewDto[]>> => {
    return axiosInstance.get(
      `/api/v1/course/${courseId}/assessment/overview`,options
    );
  }
const postApiV1Course = (
    postApiV1CourseBody?: PostApiV1CourseBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {const formData = new FormData();
if(postApiV1CourseBody?.title !== undefined) {
 formData.append(`title`, postApiV1CourseBody.title);
 }
if(postApiV1CourseBody?.description !== undefined) {
 formData.append(`description`, postApiV1CourseBody.description);
 }
if(postApiV1CourseBody?.category_id !== undefined) {
 formData.append(`category_id`, postApiV1CourseBody.category_id);
 }
if(postApiV1CourseBody?.sub_category_id !== undefined) {
 formData.append(`sub_category_id`, postApiV1CourseBody.sub_category_id);
 }
if(postApiV1CourseBody?.difficulty_level_id !== undefined) {
 formData.append(`difficulty_level_id`, postApiV1CourseBody.difficulty_level_id);
 }
if(postApiV1CourseBody?.duration_minute !== undefined) {
 formData.append(`duration_minute`, postApiV1CourseBody.duration_minute.toString())
 }
if(postApiV1CourseBody?.thumbnail_img !== undefined) {
 formData.append(`thumbnail_img`, postApiV1CourseBody.thumbnail_img);
 }
if(postApiV1CourseBody?.is_drafted !== undefined) {
 formData.append(`is_drafted`, postApiV1CourseBody.is_drafted.toString())
 }

    return axiosInstance.post(
      `/api/v1/course`,
      formData,options
    );
  }
const getApiV1Course = (
    params?: GetApiV1CourseParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedCoursesDto>> => {
    return axiosInstance.get(
      `/api/v1/course`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putApiV1CourseCourseId = (
    courseId: string,
    putApiV1CourseCourseIdBody?: PutApiV1CourseCourseIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {const formData = new FormData();
if(putApiV1CourseCourseIdBody?.title !== undefined) {
 formData.append(`title`, putApiV1CourseCourseIdBody.title);
 }
if(putApiV1CourseCourseIdBody?.description !== undefined) {
 formData.append(`description`, putApiV1CourseCourseIdBody.description);
 }
if(putApiV1CourseCourseIdBody?.category_id !== undefined) {
 formData.append(`category_id`, putApiV1CourseCourseIdBody.category_id);
 }
if(putApiV1CourseCourseIdBody?.sub_category_id !== undefined) {
 formData.append(`sub_category_id`, putApiV1CourseCourseIdBody.sub_category_id);
 }
if(putApiV1CourseCourseIdBody?.difficulty_level_id !== undefined) {
 formData.append(`difficulty_level_id`, putApiV1CourseCourseIdBody.difficulty_level_id);
 }
if(putApiV1CourseCourseIdBody?.duration_minute !== undefined) {
 formData.append(`duration_minute`, putApiV1CourseCourseIdBody.duration_minute.toString())
 }
if(putApiV1CourseCourseIdBody?.thumbnail_img !== undefined) {
 formData.append(`thumbnail_img`, putApiV1CourseCourseIdBody.thumbnail_img);
 }
if(putApiV1CourseCourseIdBody?.is_drafted !== undefined) {
 formData.append(`is_drafted`, putApiV1CourseCourseIdBody.is_drafted.toString())
 }

    return axiosInstance.put(
      `/api/v1/course/${courseId}`,
      formData,options
    );
  }
const deleteApiV1CourseCourseId = (
    courseId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.delete(
      `/api/v1/course/${courseId}`,options
    );
  }
const getApiV1CourseCourseIdLeaderboard = (
    courseId: string,
    params?: GetApiV1CourseCourseIdLeaderboardParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LeaderboardDto[]>> => {
    return axiosInstance.get(
      `/api/v1/course/${courseId}/leaderboard`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getApiV1CourseRecommendation = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CourseSummaryDto[]>> => {
    return axiosInstance.get(
      `/api/v1/course/recommendation`,options
    );
  }
const getApiV1CourseAdminSummary = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AdminCourseSummaryDto>> => {
    return axiosInstance.get(
      `/api/v1/course/admin-summary`,options
    );
  }
const getApiV1CourseIdOverview = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CourseOverviewDto>> => {
    return axiosInstance.get(
      `/api/v1/course/${id}/overview`,options
    );
  }
const getApiV1CourseCourseIdForumMessage = (
    courseId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ForumMessageDto[]>> => {
    return axiosInstance.get(
      `/api/v1/course/${courseId}/forum-message`,options
    );
  }
const postApiV1CourseCourseIdForumMessage = (
    courseId: string,
    createForumMessageRequestDto?: CreateForumMessageRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.post(
      `/api/v1/course/${courseId}/forum-message`,
      createForumMessageRequestDto,options
    );
  }
const postApiV1CourseCourseIdEnrollment = (
    courseId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.post(
      `/api/v1/course/${courseId}/enrollment`,
      undefined,options
    );
  }
const getApiV1CourseIdContent = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CourseContentResponseDto>> => {
    return axiosInstance.get(
      `/api/v1/course/${id}/content`,options
    );
  }
const getApiV1CourseIdProgress = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CourseProgressResponseDto>> => {
    return axiosInstance.get(
      `/api/v1/course/${id}/progress`,options
    );
  }
const getApiV1CourseIdAssessmentHistory = (
    id: string,
    params?: GetApiV1CourseIdAssessmentHistoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedAssessmentHistoryDto>> => {
    return axiosInstance.get(
      `/api/v1/course/${id}/assessment-history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getApiV1CourseActiveCategory = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RefTermDto[]>> => {
    return axiosInstance.get(
      `/api/v1/course/active-category`,options
    );
  }
return {getApiV1CourseCourseIdAssessmentOverview,postApiV1Course,getApiV1Course,putApiV1CourseCourseId,deleteApiV1CourseCourseId,getApiV1CourseCourseIdLeaderboard,getApiV1CourseRecommendation,getApiV1CourseAdminSummary,getApiV1CourseIdOverview,getApiV1CourseCourseIdForumMessage,postApiV1CourseCourseIdForumMessage,postApiV1CourseCourseIdEnrollment,getApiV1CourseIdContent,getApiV1CourseIdProgress,getApiV1CourseIdAssessmentHistory,getApiV1CourseActiveCategory}};
export type GetApiV1CourseCourseIdAssessmentOverviewResult = AxiosResponse<AssessmentOverviewDto[]>
export type PostApiV1CourseResult = AxiosResponse<SuccessResponse>
export type GetApiV1CourseResult = AxiosResponse<PaginatedCoursesDto>
export type PutApiV1CourseCourseIdResult = AxiosResponse<SuccessResponse>
export type DeleteApiV1CourseCourseIdResult = AxiosResponse<SuccessResponse>
export type GetApiV1CourseCourseIdLeaderboardResult = AxiosResponse<LeaderboardDto[]>
export type GetApiV1CourseRecommendationResult = AxiosResponse<CourseSummaryDto[]>
export type GetApiV1CourseAdminSummaryResult = AxiosResponse<AdminCourseSummaryDto>
export type GetApiV1CourseIdOverviewResult = AxiosResponse<CourseOverviewDto>
export type GetApiV1CourseCourseIdForumMessageResult = AxiosResponse<ForumMessageDto[]>
export type PostApiV1CourseCourseIdForumMessageResult = AxiosResponse<SuccessResponse>
export type PostApiV1CourseCourseIdEnrollmentResult = AxiosResponse<SuccessResponse>
export type GetApiV1CourseIdContentResult = AxiosResponse<CourseContentResponseDto>
export type GetApiV1CourseIdProgressResult = AxiosResponse<CourseProgressResponseDto>
export type GetApiV1CourseIdAssessmentHistoryResult = AxiosResponse<PaginatedAssessmentHistoryDto>
export type GetApiV1CourseActiveCategoryResult = AxiosResponse<RefTermDto[]>
