import { createTheme } from "@mui/material/styles";
import { typography } from "./typography";
import { lightColors, darkColors } from "./colors";

export const createAppTheme = (mode: "light" | "dark") => {
  const colors = mode === "light" ? lightColors : darkColors;
  return createTheme({
    palette: {
      mode,
      primary: colors.primary,
      secondary: colors.secondary,
      background: colors.background,
      text: colors.text,
    },
    typography,
    spacing: 8,
    components: {
      MuiTypography: {
        styleOverrides: {
          h1: { marginBottom: "1.5rem" },
          h2: { marginBottom: "1.5rem" },
          h3: { marginBottom: "0.5rem" },
          h4: { marginBottom: "0.1rem" },
          h5: { marginBottom: "0.1rem" },
          h6: { marginBottom: "0.1rem" },
          body1: { marginBottom: "0rem" },
          body2: { marginBottom: "0rem" },
          caption: { marginBottom: "0rem" },
        },
      },
      MuiCssBaseline: {
        styleOverrides: {
          ":root": {
            "--primary": colors.primary.main,
            "--on-primary": colors.onPrimary,
            "--primary-container": colors.primaryContainer,
            "--secondary": colors.secondary.main,
            "--surface": colors.background.default,
            "--surface-container-lowest": colors.background.paper,
            "--on-surface": colors.text.primary,
            "--on-surface-variant": colors.text.secondary,
            "--outline": colors.outline,
            "--outline-variant": colors.outlineVariant,
            "--error": colors.error,
            "--success": colors.success,
            "--on-success": colors.onSuccess,
            "--success-container": colors.successContainer,
            "--warning": colors.warning,
            "--on-warning": colors.onWarning,
            "--warning-container": colors.warningContainer,
            "--info": colors.info,
            "--on-info": colors.onInfo,
            "--info-container": colors.infoContainer,
            "--surface-container-high": colors.surfaceContainerHigh,
            "--surface-container": colors.surfaceContainer,
            "--surface-container-low": colors.surfaceContainerLow,
            "--error-container": colors.errorContainer,
            "--danger": colors.danger,
            "--danger-hover": colors.dangerHover,
            "--badge": colors.badge,
            "--font-body-md": typography.fontFamily,
            "--navbar-bg": colors.navbar.bg,
            "--navbar-text": colors.navbar.text,
            "--navbar-link-active": colors.navbar.linkActive,
            "--transparent": colors.transparent,
            "--card1": colors.card,
            "--card-border-icon": colors.cardBorderIcon,
            "--glass-bg": colors.glassBg,
            "--outline-subtle": colors.outlineSubtle,
            "--loader-overlay": colors.loaderOverlay,
            "--card-border": colors.cardBorder,
            "--overlay-modal": colors.overlayModal,
            "--overlay-progress": colors.overlayProgress,
            "--canvas-overlay": colors.canvasOverlay,
            "--canvas-bg": colors.canvasBg,
            "--canvas-text": colors.canvasText,
            "--canvas-border": colors.canvasBorder,
            "--quiz-bg": colors.quizBg,
            "--quiz-timer-color": colors.quizTimerColor,
            "--quiz-option-bg": colors.quizOptionBg,
            "--quiz-text-glow": colors.quizTextGlow,
            "--error-border": colors.errorBorder,
            "--shadow-xs": colors.shadows.xs,
            "--shadow-sm": colors.shadows.sm,
            "--shadow-md": colors.shadows.md,
            "--shadow-elevated": colors.shadows.elevated,
            "--shadow-focus": colors.shadows.focus,
            "--focus-ring-primary": colors.shadows.focusRingPrimary,
            "--focus-ring-error": colors.shadows.focusRingError,
            "--assessment-shadow": colors.shadows.assessmentShadow,
            "--assessment-shadow-strong": colors.shadows.assessmentShadowStrong,
            "--star-color": colors.starColor,
            "--accordion-row-hover": colors.accordionRowHover,
            "--input-label-color": colors.inputLabelColor,
            "--input-placeholder": colors.inputPlaceholder,
            "--outline-light": colors.outlineLight,
            "--outline-lighter": colors.outlineLighter,
            "--sidebar-icon-color": colors.sidebarIconColor,
            "--ghost-hover-bg": colors.ghostHoverBg,
            "--btn-home-shadow": colors.btnHomeShadow,
            "--review-own-bg": colors.reviewOwnBg,
            "--review-avatar-end": colors.reviewAvatarEnd,
            "--review-shadow": colors.reviewShadow,
            "--review-danger-bg": colors.reviewDangerBg,
            "--surface-variant": mode === "light" ? "#e0e0ea" : "#2a2a2a",
            "--secondary-container": mode === "light" ? "#4648d4" : "#2b2b76",
            "--on-secondary-container":
              mode === "light" ? "#ffffff" : "#e0e0ff",
            "--card": mode === "light" ? "#ffffff" : "#1e1e1e",
            "--table-bg": mode === "light" ? "#f5f5fc" : "#252525",
            "--card-shadow":
              mode === "light"
                ? "2px 2px 10px rgba(0,0,0,0.5)"
                : "2px 2px 10px rgba(255,255,255,0.2)",
          },
          body: {
            backgroundColor: colors.background.default,
            color: colors.text.primary,
            transition: "background-color 0.3s ease, color 0.3s ease",
            "&::before": {
              display: mode === "light" ? "block" : "none",
            },
          },
          "::selection": {
            backgroundColor: colors.selection.bg,
            color: colors.selection.text,
          },
        },
      },
    },
  });
};
