/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateReviewRequestDto,
  GetApiV1ReviewCourseCourseIdParams,
  PaginatedReviewsDto,
  ReviewDto,
  SuccessResponse,
  UpdateReviewRequestDto
} from '../../models';




  export const getReview = (axiosInstance: AxiosInstance = axios.default) => {
const postApiV1ReviewCourseCourseId = (
    courseId: string,
    createReviewRequestDto?: CreateReviewRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReviewDto>> => {
    return axiosInstance.post(
      `/api/v1/review/course/${courseId}`,
      createReviewRequestDto,options
    );
  }
const getApiV1ReviewCourseCourseId = (
    courseId: string,
    params?: GetApiV1ReviewCourseCourseIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedReviewsDto>> => {
    return axiosInstance.get(
      `/api/v1/review/course/${courseId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putApiV1ReviewId = (
    id: string,
    updateReviewRequestDto?: UpdateReviewRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReviewDto>> => {
    return axiosInstance.put(
      `/api/v1/review/${id}`,
      updateReviewRequestDto,options
    );
  }
const deleteApiV1ReviewId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.delete(
      `/api/v1/review/${id}`,options
    );
  }
const getApiV1ReviewCourseCourseIdUserUserIdReview = (
    courseId: string,
    userId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReviewDto>> => {
    return axiosInstance.get(
      `/api/v1/review/course/${courseId}/user/${userId}/review`,options
    );
  }
return {postApiV1ReviewCourseCourseId,getApiV1ReviewCourseCourseId,putApiV1ReviewId,deleteApiV1ReviewId,getApiV1ReviewCourseCourseIdUserUserIdReview}};
export type PostApiV1ReviewCourseCourseIdResult = AxiosResponse<ReviewDto>
export type GetApiV1ReviewCourseCourseIdResult = AxiosResponse<PaginatedReviewsDto>
export type PutApiV1ReviewIdResult = AxiosResponse<ReviewDto>
export type DeleteApiV1ReviewIdResult = AxiosResponse<SuccessResponse>
export type GetApiV1ReviewCourseCourseIdUserUserIdReviewResult = AxiosResponse<ReviewDto>
