export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  DISCOVER: "/discover",
  MY_COURSES: "/my-courses",
  PROFILE: "/profile",
  COURSE_OVERVIEW: "/course-overview/:id",
  COURSE_CONTENT: "/course-content/:courseId",
  ADMIN_COURSES: "/admin/courses",
  ADMIN_ENROLLMENTS: "/admin/enrollments",
  ADMIN_USERS: "/dashboard",
  ADMIN_USERS_CREATE: "/admin/users/create",
  ADMIN_USERS_EDIT: "/admin/users/:userId/edit",
  ADMIN_ASSESSMENTS: "/admin/assessments",
  ASSESSMENT_OVERVIEW: "/course-overview/:courseId/assessment",
  ASSESSMENT_TEST: "/course-content/:courseId/assessment/test",
  ASSESSMENT_HISTORY: "/assessment-history",
  ASSESSMENT_RESULT: "/course-overview/:courseId/assessment/result",
  LEADERBOARD: "/leaderboard",
  COURSE_DETAIL: "/course/:courseId",
} as const;
