/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface AdminCourseSummaryDto {
  total_courses?: number;
  published_courses?: number;
  draft_courses?: number;
  total_enrollments?: number;
  active_students?: number;
}
