/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface Answer {
  question_id?: string;
  /** @nullable */
  selected_answer?: string | null;
}
