/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface AssessmentAttemptDto {
  attempt_number?: number;
  attempted_on?: string;
  score?: number;
  weighted_score?: number;
  passed?: boolean;
}
