/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import type { AssessmentAttemptDto } from './assessmentAttemptDto';

export interface AssessmentResultResponseDto {
  assessment_id?: string;
  /** @nullable */
  assessment_title?: string | null;
  passing_mark?: number;
  /** @nullable */
  attempts?: AssessmentAttemptDto[] | null;
}
