/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import type { RefTermDto } from './refTermDto';

export interface AssessmentHistoryDto {
  id?: string;
  assessment_id?: string;
  user_id?: string;
  started_on?: string;
  completed_on?: string;
  score?: number;
  weighted_score?: number;
  tier_awarded?: RefTermDto;
  passed?: boolean;
}
