/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface CourseProgressResponseDto {
  enrollment_id?: string;
  progress_percentage?: number;
  /** @nullable */
  completed_on?: string | null;
  enrollment_status?: boolean;
}
