/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface CourseContentDetailDto {
  id?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content_type?: string | null;
  /** @nullable */
  video_url?: string | null;
  /** @nullable */
  pdf_base64?: string | null;
  sequence_order?: number;
  meta_topic_id?: string;
  /** @nullable */
  meta_topic_name?: string | null;
  meta_sequence_order?: number;
  is_completed?: boolean;
  /** @nullable */
  completed_on?: string | null;
  /** @nullable */
  previous_content_id?: string | null;
  /** @nullable */
  next_content_id?: string | null;
}
