/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface CourseOverviewContentDto {
  id?: string;
  meta_topic_id?: string;
  /** @nullable */
  title?: string | null;
  sequence_order?: number;
}
