/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface CreateForumMessageRequestDto {
  /** @nullable */
  message_text?: string | null;
}
