/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface CreateReviewRequestDto {
  rating?: number;
  /** @nullable */
  review_text?: string | null;
}
