/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import type { RefTermDto } from './refTermDto';

export interface EnrolledCourseDto {
  course_id?: string;
  /** @nullable */
  course_title?: string | null;
  category?: RefTermDto;
  difficulty_level?: RefTermDto;
  enrolled_on?: string;
  /** @nullable */
  completed_on?: string | null;
  progress_percentage?: number;
}
