/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface ErrorResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  error?: string | null;
}
