/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export type GetApiV1CourseParams = {
page?: number;
pageSize?: number;
categoryId?: string;
difficultyLevelId?: string;
status?: boolean;
search?: string;
};
