/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export type GetApiV1AssessmentParams = {
pageNumber?: number;
pageSize?: number;
};
