/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export type GetApiV1ReviewCourseCourseIdParams = {
page?: number;
pageSize?: number;
};
