/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import type { AssessmentOverviewDto } from './assessmentOverviewDto';

export interface PaginatedAssessmentsDto {
  /** @nullable */
  data?: AssessmentOverviewDto[] | null;
  total?: number;
  page?: number;
  page_size?: number;
}
