/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import type { AssessmentHistoryDto } from './assessmentHistoryDto';

export interface PaginatedAssessmentHistoryDto {
  /** @nullable */
  data?: AssessmentHistoryDto[] | null;
  total?: number;
  page?: number;
  page_size?: number;
}
