/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import type { AssessmentHistoryItemDto } from './assessmentHistoryItemDto';

export interface PaginatedAssessmentHistoryResponseDto {
  /** @nullable */
  item?: AssessmentHistoryItemDto[] | null;
  page_number?: number;
  page_size?: number;
  total_records?: number;
}
