/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import type { UserDetailDto } from './userDetailDto';

export interface PaginatedUsersDto {
  /** @nullable */
  data?: UserDetailDto[] | null;
  total?: number;
  page?: number;
  page_size?: number;
}
