/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import type { ReviewDto } from './reviewDto';

export interface PaginatedReviewsDto {
  /** @nullable */
  data?: ReviewDto[] | null;
  total?: number;
  page?: number;
  page_size?: number;
}
