/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface SubmitAnswerReviewDto {
  question_id?: string;
  /** @nullable */
  question_text?: string | null;
  /** @nullable */
  selected_answer?: string | null;
  is_correct?: boolean;
  obtained_score?: number;
}
