/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface SuccessResponse {
  id?: string;
  /** @nullable */
  message?: string | null;
}
