/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface UpdateUserRequestDto {
  /** @nullable */
  full_name?: string | null;
  /** @nullable */
  mobile_number?: string | null;
  designation_id?: string;
  gender_id?: string;
}
