/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface UpdateContentCompletionStatusRequest {
  is_completed?: boolean;
}
