/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface UpdateContentCompletionStatusResponse {
  course_content_id?: string;
  is_completed?: boolean;
  /** @nullable */
  completed_on?: string | null;
  course_progress_percentage?: number;
}
