/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */

export interface WeakTopicDto {
  meta_topic_id?: string;
  /** @nullable */
  topic_name?: string | null;
  average_score?: number;
  failed_attempts?: number;
}
