// <auto-generated />
using System;
using LAP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LAP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LearningAssessmentDbContext))]
    partial class LearningAssessmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LAP")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LAP.Domain.Entity.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinute")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minute");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PassingMark")
                        .HasColumnType("integer")
                        .HasColumnName("passing_mark");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalMark")
                        .HasColumnType("integer")
                        .HasColumnName("total_mark");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_assessment");

                    b.HasIndex("CourseId")
                        .IsUnique()
                        .HasDatabaseName("i_x_assessment_course_id")
                        .HasFilter("is_active = true");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_assessment_is_active");

                    b.ToTable("assessment", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.AssessmentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentHistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_history_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<decimal>("ObtainedScore")
                        .HasColumnType("numeric")
                        .HasColumnName("obtained_score");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selected_answer");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_assessment_answer");

                    b.HasIndex("AssessmentHistoryId")
                        .HasDatabaseName("i_x_assessment_answer_assessment_history_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_assessment_answer_is_active");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("i_x_assessment_answer_question_id");

                    b.ToTable("assessment_answer", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.AssessmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on");

                    b.Property<Guid?>("TierAwardedId")
                        .HasColumnType("uuid")
                        .HasColumnName("tier_awarded_id");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeightedScore")
                        .HasColumnType("numeric")
                        .HasColumnName("weighted_score");

                    b.HasKey("Id")
                        .HasName("p_k_assessment_history");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("i_x_assessment_history_assessment_id");

                    b.HasIndex("CompletedOn")
                        .HasDatabaseName("i_x_assessment_history_completed_on");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_assessment_history_is_active");

                    b.HasIndex("StartedOn")
                        .HasDatabaseName("i_x_assessment_history_started_on");

                    b.HasIndex("TierAwardedId")
                        .HasDatabaseName("i_x_assessment_history_tier_awarded_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_assessment_history_user_id");

                    b.HasIndex("UserId", "AssessmentId")
                        .HasDatabaseName("i_x_assessment_history_user_id_assessment_id");

                    b.ToTable("assessment_history", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DifficultyLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("difficulty_level_id");

                    b.Property<int>("DurationMinute")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minute");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDrafted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_drafted");

                    b.Property<decimal>("OverallRating")
                        .HasColumnType("numeric")
                        .HasColumnName("overall_rating");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_category_id");

                    b.Property<string>("ThumbnailImgPath")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_img_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_course");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_course_category_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("i_x_course_created_by_user_id");

                    b.HasIndex("DifficultyLevelId")
                        .HasDatabaseName("i_x_course_difficulty_level_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_course_is_active");

                    b.HasIndex("SubCategoryId")
                        .HasDatabaseName("i_x_course_sub_category_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("i_x_course_title");

                    b.ToTable("course", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.CourseContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_type_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MetaTopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("meta_topic_id");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("text")
                        .HasColumnName("pdf_file_path");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("p_k_course_content");

                    b.HasIndex("ContentTypeId")
                        .HasDatabaseName("i_x_course_content_content_type_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_course_content_is_active");

                    b.HasIndex("MetaTopicId")
                        .HasDatabaseName("i_x_course_content_meta_topic_id");

                    b.HasIndex("MetaTopicId", "SequenceOrder")
                        .HasDatabaseName("i_x_course_content_meta_topic_id_sequence_order");

                    b.ToTable("course_content", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.CourseMetaTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<int>("DurationMinute")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minute");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_course_meta_topic");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("i_x_course_meta_topic_course_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_course_meta_topic_is_active");

                    b.HasIndex("CourseId", "SequenceOrder")
                        .HasDatabaseName("i_x_course_meta_topic_course_id_sequence_order");

                    b.ToTable("course_meta_topic", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_on");

                    b.Property<bool>("EnrollmentStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("enrollment_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("progress_percentage");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_enrollment");

                    b.HasIndex("CompletedOn")
                        .HasDatabaseName("i_x_enrollment_completed_on");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("i_x_enrollment_course_id");

                    b.HasIndex("EnrolledOn")
                        .HasDatabaseName("i_x_enrollment_enrolled_on");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_enrollment_is_active");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_enrollment_user_id");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("i_x_enrollment_user_id_course_id");

                    b.ToTable("enrollment", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_feature");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_feature_is_active");

                    b.HasIndex("Method")
                        .HasDatabaseName("i_x_feature_method");

                    b.ToTable("feature", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.ForumMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_forum_message");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("i_x_forum_message_course_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_forum_message_is_active");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_forum_message_user_id");

                    b.HasIndex("CourseId", "UserId")
                        .HasDatabaseName("i_x_forum_message_course_id_user_id");

                    b.ToTable("forum_message", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("failed_records");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ProcessedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("processed_records");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_import_job");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("i_x_import_job_assessment_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_import_job_is_active");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("i_x_import_job_status_id");

                    b.ToTable("import_job", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<Guid>("DesignationId")
                        .HasColumnType("uuid")
                        .HasColumnName("designation_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("gender_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mobile_number");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_person");

                    b.HasIndex("DesignationId")
                        .HasDatabaseName("i_x_person_designation_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_person_email");

                    b.HasIndex("GenderId")
                        .HasDatabaseName("i_x_person_gender_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_person_is_active");

                    b.ToTable("person", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MetaTopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("meta_topic_id");

                    b.Property<string>("OptionList")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("option_list");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_type_id");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_k_question");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("i_x_question_assessment_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_question_is_active");

                    b.HasIndex("MetaTopicId")
                        .HasDatabaseName("i_x_question_meta_topic_id");

                    b.HasIndex("QuestionTypeId")
                        .HasDatabaseName("i_x_question_question_type_id");

                    b.HasIndex("AssessmentId", "MetaTopicId")
                        .HasDatabaseName("i_x_question_assessment_id_meta_topic_id");

                    b.ToTable("question", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.RefSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ref_set");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_ref_set_is_active");

                    b.ToTable("ref_set", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.RefTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RefSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_set_id");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ref_term");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_ref_term_is_active");

                    b.HasIndex("RefSetId")
                        .HasDatabaseName("i_x_ref_term_ref_set_id");

                    b.ToTable("ref_term", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_token");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_refresh_token_is_active");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_refresh_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_refresh_token_user_id");

                    b.ToTable("refresh_token", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_review");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("i_x_review_course_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_review_is_active");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_review_user_id");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("i_x_review_user_id_course_id");

                    b.ToTable("review", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.RoleFeatureMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_role_feature_mapping");

                    b.HasIndex("FeatureId")
                        .HasDatabaseName("i_x_role_feature_mapping_feature_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_role_feature_mapping_is_active");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_role_feature_mapping_role_id");

                    b.HasIndex("RoleId", "FeatureId")
                        .HasDatabaseName("i_x_role_feature_mapping_role_id_feature_id");

                    b.ToTable("role_feature_mapping", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_tier_id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric")
                        .HasColumnName("overall_score");

                    b.Property<decimal>("OverallWeightedScore")
                        .HasColumnType("numeric")
                        .HasColumnName("overall_weighted_score");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_user");

                    b.HasIndex("CurrentTierId")
                        .HasDatabaseName("i_x_user_current_tier_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_user_is_active");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_person_id");

                    b.ToTable("user", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.UserCourseProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on");

                    b.Property<Guid>("CourseContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_content_id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_user_course_progress");

                    b.HasIndex("CourseContentId")
                        .HasDatabaseName("i_x_user_course_progress_course_content_id");

                    b.HasIndex("EnrollmentId")
                        .HasDatabaseName("i_x_user_course_progress_enrollment_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_user_course_progress_is_active");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("i_x_user_course_progress_is_completed");

                    b.HasIndex("EnrollmentId", "CourseContentId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_course_progress_enrollment_id_course_content_id");

                    b.ToTable("user_course_progress", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.UserRoleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_role_mapping");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_user_role_mapping_is_active");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_user_role_mapping_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_role_mapping_user_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_role_mapping_user_id_role_id");

                    b.ToTable("user_role_mapping", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.UserSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_secret");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_user_secret_is_active");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_secret_user_id");

                    b.ToTable("user_secret", "LAP");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Assessment", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Course", "Course")
                        .WithOne("Assessment")
                        .HasForeignKey("LAP.Domain.Entity.Assessment", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assessment__course_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LAP.Domain.Entity.AssessmentAnswer", b =>
                {
                    b.HasOne("LAP.Domain.Entity.AssessmentHistory", "AssessmentHistory")
                        .WithMany("Answers")
                        .HasForeignKey("AssessmentHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assessment_answer__assessment_history_assessment_history_id");

                    b.HasOne("LAP.Domain.Entity.Question", "Question")
                        .WithMany("AssessmentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assessment_answer__question_question_id");

                    b.Navigation("AssessmentHistory");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LAP.Domain.Entity.AssessmentHistory", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Assessment", "Assessment")
                        .WithMany("AssessmentHistories")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assessment_history_assessment_assessment_id");

                    b.HasOne("LAP.Domain.Entity.RefTerm", "TierAwarded")
                        .WithMany()
                        .HasForeignKey("TierAwardedId")
                        .HasConstraintName("f_k_assessment_history__ref_term_tier_awarded_id");

                    b.HasOne("LAP.Domain.Entity.User", "User")
                        .WithMany("AssessmentHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assessment_history__user_user_id");

                    b.Navigation("Assessment");

                    b.Navigation("TierAwarded");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Course", b =>
                {
                    b.HasOne("LAP.Domain.Entity.RefTerm", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course__ref_term_category_id");

                    b.HasOne("LAP.Domain.Entity.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course__user_created_by_user_id");

                    b.HasOne("LAP.Domain.Entity.RefTerm", "DifficultyLevel")
                        .WithMany()
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course__ref_term_difficulty_level_id");

                    b.HasOne("LAP.Domain.Entity.RefTerm", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course__ref_term_sub_category_id");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DifficultyLevel");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("LAP.Domain.Entity.CourseContent", b =>
                {
                    b.HasOne("LAP.Domain.Entity.RefTerm", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_content__ref_term_content_type_id");

                    b.HasOne("LAP.Domain.Entity.CourseMetaTopic", "MetaTopic")
                        .WithMany("Contents")
                        .HasForeignKey("MetaTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_content__course_meta_topic_meta_topic_id");

                    b.Navigation("ContentType");

                    b.Navigation("MetaTopic");
                });

            modelBuilder.Entity("LAP.Domain.Entity.CourseMetaTopic", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_meta_topic_course_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Enrollment", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_enrollment_course_course_id");

                    b.HasOne("LAP.Domain.Entity.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_enrollment__user_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAP.Domain.Entity.ForumMessage", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Course", "Course")
                        .WithMany("ForumMessages")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_forum_message_course_course_id");

                    b.HasOne("LAP.Domain.Entity.User", "User")
                        .WithMany("ForumMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_forum_message__user_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAP.Domain.Entity.ImportJob", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Assessment", "Assessment")
                        .WithMany("ImportJobs")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_import_job_assessment_assessment_id");

                    b.HasOne("LAP.Domain.Entity.RefTerm", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_import_job__ref_term_status_id");

                    b.Navigation("Assessment");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Person", b =>
                {
                    b.HasOne("LAP.Domain.Entity.RefTerm", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person__ref_term_designation_id");

                    b.HasOne("LAP.Domain.Entity.RefTerm", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person__ref_term_gender_id");

                    b.Navigation("Designation");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Question", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_question_assessment_assessment_id");

                    b.HasOne("LAP.Domain.Entity.CourseMetaTopic", "MetaTopic")
                        .WithMany("Questions")
                        .HasForeignKey("MetaTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_question_course_meta_topic_meta_topic_id");

                    b.HasOne("LAP.Domain.Entity.RefTerm", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_question__ref_term_question_type_id");

                    b.Navigation("Assessment");

                    b.Navigation("MetaTopic");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("LAP.Domain.Entity.RefTerm", b =>
                {
                    b.HasOne("LAP.Domain.Entity.RefSet", "RefSet")
                        .WithMany("RefTerms")
                        .HasForeignKey("RefSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ref_term_ref_set_ref_set_id");

                    b.Navigation("RefSet");
                });

            modelBuilder.Entity("LAP.Domain.Entity.RefreshToken", b =>
                {
                    b.HasOne("LAP.Domain.Entity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_refresh_token__user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Review", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_review_course_course_id");

                    b.HasOne("LAP.Domain.Entity.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_review__user_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAP.Domain.Entity.RoleFeatureMapping", b =>
                {
                    b.HasOne("LAP.Domain.Entity.Feature", "Feature")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_role_feature_mapping_feature_feature_id");

                    b.HasOne("LAP.Domain.Entity.RefTerm", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_role_feature_mapping_ref_term_role_id");

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LAP.Domain.Entity.User", b =>
                {
                    b.HasOne("LAP.Domain.Entity.RefTerm", "CurrentTier")
                        .WithMany()
                        .HasForeignKey("CurrentTierId")
                        .HasConstraintName("f_k_user_ref_term_current_tier_id");

                    b.HasOne("LAP.Domain.Entity.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("LAP.Domain.Entity.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_person_person_id");

                    b.Navigation("CurrentTier");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LAP.Domain.Entity.UserCourseProgress", b =>
                {
                    b.HasOne("LAP.Domain.Entity.CourseContent", "CourseContent")
                        .WithMany("UserCourseProgresses")
                        .HasForeignKey("CourseContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_course_progress_course_content_course_content_id");

                    b.HasOne("LAP.Domain.Entity.Enrollment", "Enrollment")
                        .WithMany("ProgressItems")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_course_progress_enrollment_enrollment_id");

                    b.Navigation("CourseContent");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("LAP.Domain.Entity.UserRoleMapping", b =>
                {
                    b.HasOne("LAP.Domain.Entity.RefTerm", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_role_mapping_ref_term_role_id");

                    b.HasOne("LAP.Domain.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_role_mapping_user_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAP.Domain.Entity.UserSecret", b =>
                {
                    b.HasOne("LAP.Domain.Entity.User", "User")
                        .WithOne("UserSecret")
                        .HasForeignKey("LAP.Domain.Entity.UserSecret", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_secret_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Assessment", b =>
                {
                    b.Navigation("AssessmentHistories");

                    b.Navigation("ImportJobs");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LAP.Domain.Entity.AssessmentHistory", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Course", b =>
                {
                    b.Navigation("Assessment");

                    b.Navigation("Enrollments");

                    b.Navigation("ForumMessages");

                    b.Navigation("Reviews");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("LAP.Domain.Entity.CourseContent", b =>
                {
                    b.Navigation("UserCourseProgresses");
                });

            modelBuilder.Entity("LAP.Domain.Entity.CourseMetaTopic", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Enrollment", b =>
                {
                    b.Navigation("ProgressItems");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Feature", b =>
                {
                    b.Navigation("RoleFeatures");
                });

            modelBuilder.Entity("LAP.Domain.Entity.Person", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("LAP.Domain.Entity.Question", b =>
                {
                    b.Navigation("AssessmentAnswers");
                });

            modelBuilder.Entity("LAP.Domain.Entity.RefSet", b =>
                {
                    b.Navigation("RefTerms");
                });

            modelBuilder.Entity("LAP.Domain.Entity.User", b =>
                {
                    b.Navigation("AssessmentHistories");

                    b.Navigation("Enrollments");

                    b.Navigation("ForumMessages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSecret")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
