/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequestDto,
  RefreshRequestDto,
  RegisterRequestDto
} from '../../models';




  export const getAuth = (axiosInstance: AxiosInstance = axios.default) => {
const postApiV1AuthRegister = (
    registerRequestDto?: RegisterRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/auth/register`,
      registerRequestDto,options
    );
  }
const postApiV1AuthLogin = (
    loginRequestDto?: LoginRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/auth/login`,
      loginRequestDto,options
    );
  }
const postApiV1AuthRefresh = (
    refreshRequestDto?: RefreshRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/auth/refresh`,
      refreshRequestDto,options
    );
  }
const postApiV1AuthLogout = (
    refreshRequestDto?: RefreshRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/auth/logout`,
      refreshRequestDto,options
    );
  }
return {postApiV1AuthRegister,postApiV1AuthLogin,postApiV1AuthRefresh,postApiV1AuthLogout}};
export type PostApiV1AuthRegisterResult = AxiosResponse<void>
export type PostApiV1AuthLoginResult = AxiosResponse<void>
export type PostApiV1AuthRefreshResult = AxiosResponse<void>
export type PostApiV1AuthLogoutResult = AxiosResponse<void>
