/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetApiV1LeaderboardOverallParams,
  LeaderboardDto
} from '../../models';




  export const getLeaderboard = (axiosInstance: AxiosInstance = axios.default) => {
const getApiV1LeaderboardOverall = (
    params?: GetApiV1LeaderboardOverallParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LeaderboardDto[]>> => {
    return axiosInstance.get(
      `/api/v1/leaderboard/overall`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getApiV1LeaderboardOverall}};
export type GetApiV1LeaderboardOverallResult = AxiosResponse<LeaderboardDto[]>
