/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetApiV1UserParams,
  PaginatedUsersDto,
  PostApiV1UserProfileImageBody,
  SuccessResponse,
  UpdateUserRequestDto,
  UserDetailDto,
  UserEnrichedDto,
  UserProfileDto
} from '../../models';




  export const getUser = (axiosInstance: AxiosInstance = axios.default) => {
const postApiV1UserProfileImage = (
    postApiV1UserProfileImageBody?: PostApiV1UserProfileImageBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {const formData = new FormData();
if(postApiV1UserProfileImageBody?.file !== undefined) {
 formData.append(`file`, postApiV1UserProfileImageBody.file);
 }

    return axiosInstance.post(
      `/api/v1/user/profile-image`,
      formData,options
    );
  }
const getApiV1User = (
    params?: GetApiV1UserParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedUsersDto>> => {
    return axiosInstance.get(
      `/api/v1/user`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getApiV1UserId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserEnrichedDto>> => {
    return axiosInstance.get(
      `/api/v1/user/${id}`,options
    );
  }
const putApiV1UserId = (
    id: string,
    updateUserRequestDto?: UpdateUserRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDetailDto>> => {
    return axiosInstance.put(
      `/api/v1/user/${id}`,
      updateUserRequestDto,options
    );
  }
const deleteApiV1UserId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.delete(
      `/api/v1/user/${id}`,options
    );
  }
const getApiV1UserIdProfile = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserProfileDto>> => {
    return axiosInstance.get(
      `/api/v1/user/${id}/profile`,options
    );
  }
return {postApiV1UserProfileImage,getApiV1User,getApiV1UserId,putApiV1UserId,deleteApiV1UserId,getApiV1UserIdProfile}};
export type PostApiV1UserProfileImageResult = AxiosResponse<SuccessResponse>
export type GetApiV1UserResult = AxiosResponse<PaginatedUsersDto>
export type GetApiV1UserIdResult = AxiosResponse<UserEnrichedDto>
export type PutApiV1UserIdResult = AxiosResponse<UserDetailDto>
export type DeleteApiV1UserIdResult = AxiosResponse<SuccessResponse>
export type GetApiV1UserIdProfileResult = AxiosResponse<UserProfileDto>
