/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetApiV1EnrollmentParams,
  PaginatedEnrollmentsDto,
  SuccessResponse,
  UpdateEnrollmentRequestDto
} from '../../models';




  export const getEnrollment = (axiosInstance: AxiosInstance = axios.default) => {
const putApiV1EnrollmentId = (
    id: string,
    updateEnrollmentRequestDto?: UpdateEnrollmentRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.put(
      `/api/v1/enrollment/${id}`,
      updateEnrollmentRequestDto,options
    );
  }
const getApiV1Enrollment = (
    params?: GetApiV1EnrollmentParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedEnrollmentsDto>> => {
    return axiosInstance.get(
      `/api/v1/enrollment`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {putApiV1EnrollmentId,getApiV1Enrollment}};
export type PutApiV1EnrollmentIdResult = AxiosResponse<SuccessResponse>
export type GetApiV1EnrollmentResult = AxiosResponse<PaginatedEnrollmentsDto>
