/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CourseContentDetailDto,
  PostApiV1CourseContentBody,
  PutApiV1CourseContentIdBody,
  SuccessResponse,
  UpdateContentCompletionStatusRequest,
  UpdateContentCompletionStatusResponse
} from '../../models';




  export const getCourseContent = (axiosInstance: AxiosInstance = axios.default) => {
const getApiV1CourseContentId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CourseContentDetailDto>> => {
    return axiosInstance.get(
      `/api/v1/course-content/${id}`,options
    );
  }
const putApiV1CourseContentId = (
    id: string,
    putApiV1CourseContentIdBody?: PutApiV1CourseContentIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {const formData = new FormData();
if(putApiV1CourseContentIdBody?.course_id !== undefined) {
 formData.append(`course_id`, putApiV1CourseContentIdBody.course_id);
 }
if(putApiV1CourseContentIdBody?.meta_topic !== undefined) {
 formData.append(`meta_topic`, putApiV1CourseContentIdBody.meta_topic);
 }
if(putApiV1CourseContentIdBody?.meta_topic_order !== undefined) {
 formData.append(`meta_topic_order`, putApiV1CourseContentIdBody.meta_topic_order.toString())
 }
if(putApiV1CourseContentIdBody?.meta_duration_minute !== undefined) {
 formData.append(`meta_duration_minute`, putApiV1CourseContentIdBody.meta_duration_minute.toString())
 }
if(putApiV1CourseContentIdBody?.title !== undefined) {
 formData.append(`title`, putApiV1CourseContentIdBody.title);
 }
if(putApiV1CourseContentIdBody?.content_type_id !== undefined) {
 formData.append(`content_type_id`, putApiV1CourseContentIdBody.content_type_id);
 }
if(putApiV1CourseContentIdBody?.video_url !== undefined) {
 formData.append(`video_url`, putApiV1CourseContentIdBody.video_url);
 }
if(putApiV1CourseContentIdBody?.pdf_file !== undefined) {
 formData.append(`pdf_file`, putApiV1CourseContentIdBody.pdf_file);
 }
if(putApiV1CourseContentIdBody?.sequence_order !== undefined) {
 formData.append(`sequence_order`, putApiV1CourseContentIdBody.sequence_order.toString())
 }

    return axiosInstance.put(
      `/api/v1/course-content/${id}`,
      formData,options
    );
  }
const deleteApiV1CourseContentId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axiosInstance.delete(
      `/api/v1/course-content/${id}`,options
    );
  }
const postApiV1CourseContent = (
    postApiV1CourseContentBody?: PostApiV1CourseContentBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {const formData = new FormData();
if(postApiV1CourseContentBody?.course_id !== undefined) {
 formData.append(`course_id`, postApiV1CourseContentBody.course_id);
 }
if(postApiV1CourseContentBody?.meta_topic !== undefined) {
 formData.append(`meta_topic`, postApiV1CourseContentBody.meta_topic);
 }
if(postApiV1CourseContentBody?.meta_topic_order !== undefined) {
 formData.append(`meta_topic_order`, postApiV1CourseContentBody.meta_topic_order.toString())
 }
if(postApiV1CourseContentBody?.meta_duration_minute !== undefined) {
 formData.append(`meta_duration_minute`, postApiV1CourseContentBody.meta_duration_minute.toString())
 }
if(postApiV1CourseContentBody?.title !== undefined) {
 formData.append(`title`, postApiV1CourseContentBody.title);
 }
if(postApiV1CourseContentBody?.content_type_id !== undefined) {
 formData.append(`content_type_id`, postApiV1CourseContentBody.content_type_id);
 }
if(postApiV1CourseContentBody?.video_url !== undefined) {
 formData.append(`video_url`, postApiV1CourseContentBody.video_url);
 }
if(postApiV1CourseContentBody?.pdf_file !== undefined) {
 formData.append(`pdf_file`, postApiV1CourseContentBody.pdf_file);
 }
if(postApiV1CourseContentBody?.sequence_order !== undefined) {
 formData.append(`sequence_order`, postApiV1CourseContentBody.sequence_order.toString())
 }

    return axiosInstance.post(
      `/api/v1/course-content`,
      formData,options
    );
  }
const putApiV1CourseContentIdCompletionStatus = (
    id: string,
    updateContentCompletionStatusRequest?: UpdateContentCompletionStatusRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateContentCompletionStatusResponse>> => {
    return axiosInstance.put(
      `/api/v1/course-content/${id}/completion-status`,
      updateContentCompletionStatusRequest,options
    );
  }
return {getApiV1CourseContentId,putApiV1CourseContentId,deleteApiV1CourseContentId,postApiV1CourseContent,putApiV1CourseContentIdCompletionStatus}};
export type GetApiV1CourseContentIdResult = AxiosResponse<CourseContentDetailDto>
export type PutApiV1CourseContentIdResult = AxiosResponse<SuccessResponse>
export type DeleteApiV1CourseContentIdResult = AxiosResponse<SuccessResponse>
export type PostApiV1CourseContentResult = AxiosResponse<SuccessResponse>
export type PutApiV1CourseContentIdCompletionStatusResult = AxiosResponse<UpdateContentCompletionStatusResponse>
