/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Learning Assessment Portal API
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  RefTermDto
} from '../../models';




  export const getReferenceData = (axiosInstance: AxiosInstance = axios.default) => {
const getApiV1ReferenceDataRefSetName = (
    refSetName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RefTermDto[]>> => {
    return axiosInstance.get(
      `/api/v1/reference-data/${refSetName}`,options
    );
  }
return {getApiV1ReferenceDataRefSetName}};
export type GetApiV1ReferenceDataRefSetNameResult = AxiosResponse<RefTermDto[]>
